"""Exactly 50 unique Execution Phrases."""

ANIME_WORDS = [
    "Bankai",
    "Domain Expansion",
    "Hollow Purple",
    "Gear Fifth",
    "Gear Second",
    "Gear Fourth",
    "Ashura Mode",
    "Rinnegan Activation",
    "Mangekyo Sharingan",
    "Eternal Mangekyo",
    "Six Paths Mode",
    "Kurama Link",
    "Rasengan Surge",
    "Chidori Strike",
    "Getsuga Tensho",
    "Mugetsu",
    "Black Flash",
    "Reverse Cursed Technique",
    "Malevolent Shrine",
    "Infinity Void",
    "Limitless",
    "Blue Technique",
    "Red Technique",
    "Cursed Energy Flow",
    "Soul Reaper Form",
    "Quincy Vollstandig",
    "Zangetsu Release",
    "Flame Breathing",
    "Water Breathing",
    "Thunder Breathing",
    "Sun Breathing",
    "Beast Breathing",
    "Dragon Slayer Mode",
    "Spirit Gun",
    "Demon Form",
    "Full Counter",
    "Overdrive",
    "Hyper Mode",
    "Final Getsuga",
    "Godspeed",
    "Lightning Cloak",
    "Shadow Clone Surge",
    "Truth Seeking Orbs",
    "Meteor Strike",
    "Void Collapse",
    "Energy Convergence",
    "Quantum Break",
    "Infinity Pulse",
    "System Override",
    "Ultra Sync"
]